FROM mcr.microsoft.com/devcontainers/go:1-1.22-bookworm

# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends postgresql-client \
#     && apt install apt-transport-https curl gnupg -y\
#     && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
# RUN mv bazel-archive-keyring.gpg /usr/share/keyrings &&\
#     echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment the next lines to use go get to install anything else you need
# USER vscode
# RUN go get -x <your-dependency-or-tool>
# USER root

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
# sudo apt install apt-transport-https curl gnupg -y
# curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
# go run server-student/main.go 
# make compile
# go get google.golang.org/grpc/reflection
# go run server-student/main.go 
# go get github.com/lib/pq
# go run server-student/main.go 
# psql
# uname -v
# sudo apt install apt-transport-https gnupg -y
# curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
# sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
# echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
# sudo apt update && sudo apt install bazel
# sudo apt update && sudo apt full-upgrade
# sudo apt install bazel-1.0.0
# sudo apt install python
# sudo apt install python3
# sudo apt install bazel-1.0.0
# python
# sudo apt update && sudo apt install bazel
# go install github.com/bazelbuild/bazel-gazelle/cmd/gazelle@latest
# gazelle -go_prefix sem-hm/golang-proto